### ISSUE TITLE
树莓派4b om_find_topic函数超时

### ISSUE THREAD

**Issue by cjpthree** [Jiu-xiao/OneMessage#2]
树莓派4b，官方64位系统运行单元测试，部分用例通过，部分用例失败，日志
----------------------日志start--------------------------------
pi@raspberrypi:~/work/midea/subpub/OneMessage/build $ make; make test ARGS="-V"
[ 37%] Built target OneMessage
[ 51%] Built target Test
[100%] Built target om_test
Running tests...
UpdateCTestConfiguration  from :/home/pi/work/midea/subpub/OneMessage/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/pi/work/midea/subpub/OneMessage/build/DartConfiguration.tcl
Test project /home/pi/work/midea/subpub/OneMessage/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: om_test

1: Test command: /home/pi/work/midea/subpub/OneMessage/build/test/om_test
1: Test timeout computed to be: 10000000
1: Running suite(s): 底层API测试
1: 100%: Checks: 2, Failures: 0, Errors: 0
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_base.c:8:P:内存分配测试:_MALLOC:0: Passed
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_base.c:13:P:互斥锁测试:_MUTEX:0: Passed
1: Running suite(s): 模块测试
1: /home/pi/work/midea/subpub/OneMessage/src/app/om_fmt.c 40: len is 4
1: /home/pi/work/midea/subpub/OneMessage/src/app/om_fmt.c 40: len is 20
1: /home/pi/work/midea/subpub/OneMessage/src/app/om_fmt.c 40: len is 20
1: /home/pi/work/midea/subpub/OneMessage/src/app/om_fmt.c 40: len is 20
1: /home/pi/work/midea/subpub/OneMessage/src/app/om_fmt.c 40: len is 20
1: 71%: Checks: 7, Failures: 0, Errors: 2
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_module.c:102:P:日志测试:_LOG:0: Passed
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_module.c:43:E:订阅发布测试:_PUBLISH:0: (after this point) Test timeout expired
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_module.c:76:E:静态订阅发布测试:_PUBLISH_STATIC:0: (after this point) Test timeout expired
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_module.c:134:P:事件触发测试:_EVENT:0: Passed
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_module.c:160:P:静态事件触发测试:_EVENT_STATIC:0: Passed
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_module.c:228:P:高级过滤器测试:_FILTER:0: Passed
1: /home/pi/work/midea/subpub/OneMessage/test/om_test_module.c:294:P:静态高级过滤器测试:_FILTER_STATIC:0: Passed
1/1 Test #1: om_test ..........................***Failed   10.04 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  10.04 sec

The following tests FAILED:
          1 - om_test (Failed)
Errors while running CTest
----------------------日志end--------------------------------

自己编写demo运行，发现是om_find_topic函数超时了，请作者看看这问题。

**Comment by cjpthree** [comment]
树莓派4b执行make test超时失败的情况，代码是当前master分支最新一次提交（commit 5d2dc883e828cc2b1b48a3b59268ba2904f7b30a），我没有修改。
我的demo看附件。
[linux-cmake-subpub.tar.gz](https://github.com/Jiu-xiao/OneMessage/files/10276386/linux-cmake-subpub.tar.gz)
作为对比，无论make test测试，还是demo执行，在amd64 ubuntu电脑下都是成功的，但在arm64 debian树莓派下都是失败的。

**Comment by Jiu-xiao** [comment]
我现在没有对应的硬件，无法复现bug。你能不能使用gdb调试一下demo程序，提供一下出现问题时的堆栈调用

**Comment by cjpthree** [comment]
这样效率比较低，不如我明晚把树莓派拿回家后，给你开个调试通道吧，让你直接通过ssh连上我的树莓派调试。

**Comment by Jiu-xiao** [comment]
已修复：https://github.com/Jiu-xiao/OneMessage/commit/c957fbfabcccd0a6fa194664c2eade61021b5357

**Comment by cjpthree** [comment]
验证问题解决
